language: python
sudo: false
cache: pip
python:
    - '3.5'
os:
    - linux
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7-django1.11
    - TOXENV=3.4-django2.0
    - TOXENV=3.4-django1.11
    - TOXENV=3.5-django2.0
    - TOXENV=3.5-django1.11
    - TOXENV=3.6-django2.0
    - TOXENV=3.6-django1.11
    - TOXENV=3.7-django2.0
    - TOXENV=3.7-django1.11
    - TOXENV=flake8
    - TOXENV=flakeplus
    - TOXENV=apicheck
    - TOXENV=pydocstyle
    - TOXENV=cov

matrix:
  include:
    - python: pypy
      env: TOXENV=pypy-django1.11

install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
