version: '3.9'
services:

  migrate:
    image: &image django-celery-results:latest
    build:
      context: ../..
      dockerfile: reproduce/rep194/Dockerfile
    env_file:
      - defaults.env
    depends_on:
      - postgres
      - redis
    volumes:
        - ../..:/app
    command: -c "python manage.py migrate"

  celery-worker:
    image: *image
    depends_on:
      - redis
      - migrate
    env_file:
      - defaults.env
    volumes:
      - ../..:/app
    command: -c "celery -A reproduce.rep194 worker -l info"

# Supporting services
  postgres:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - defaults.env

  redis:
    image: redis:alpine
    restart: always

volumes:
  dbdata:
